### ISSUE TITLE
1.0.0 fails to run with chef-client v13+

### ISSUE THREAD

**Issue by jas0nfl0yd** [CopperEgg/chef-copperegg#21]
chef-client 13.0.118 fails when running the copperegg cookbook.  Doesn't matter if the node has a role assigned or not.

```
NoMethodError
-------------
undefined method `roles' for #<Chef::Node::Attribute:0x00000002a06200>

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/copperegg/recipes/default.rb:21:in `from_file'
  /var/chef/cache/cookbooks/rpc_copperegg/recipes/default.rb:10:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/copperegg/recipes/default.rb:

 14:  copperegg_url = node['copperegg']['url']
 15:
 16:  chef_server_tags = []
 17:
 18:  chef_server_tags.push(node.chef_environment) if node['copperegg']['include_env_astag']
 19:
 20:  # Add any chef roles to the list
 21>> node.roles.each do |role|
 22:    chef_server_tags.push(role)
 23:  end if node['copperegg']['include_roles_astags']
 24:
 25:  node.tags.each do |tag|
 26:    chef_server_tags.push(tag)
 27:  end if node['copperegg']['include_node_tags']
 28:
 29:  node.set['copperegg']['alltags'] = node['copperegg']['tags'] + chef_server_tags
 30:
```

**Comment by Neelakshi1808** [comment]
Fix issue in cookbook v1.2.0.
